name: Lightweight Linux RDP with Playit

on:
  workflow_dispatch:

jobs:
  setup-light-rdp:
    runs-on: ubuntu-latest

    steps:
    - name: Install Openbox and xrdp (fixed version)
      run: |
        sudo apt update
        sudo apt install -y xrdp openbox tint2 xterm dbus-x11
        echo "exec openbox-session" > ~/.xsession
        echo "exec openbox-session" > ~/.xinitrc
        chmod +x ~/.xsession ~/.xinitrc
        sudo adduser runner ssl-cert
        sudo systemctl enable xrdp
        sudo systemctl restart xrdp

    - name: Set password for default user
      run: |
        echo 'runner:p@ssw0rd!' | sudo chpasswd

    - name: Install Playit from official repo
      run: |
        curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/playit.gpg >/dev/null
        echo "deb [signed-by=/etc/apt/trusted.gpg.d/playit.gpg] https://playit-cloud.github.io/ppa/data ./" | sudo tee /etc/apt/sources.list.d/playit-cloud.list
        sudo apt update
        sudo apt install -y playit

    - name: Run Playit with Auth Key
      run: |
        playit --secret 7926284faf370476c927d1b4e0a8204e808c4fa9d1088f3d20fc645056b40004
