name: Linux RDP with Playit Tunnel

on:
  workflow_dispatch:

jobs:
  setup-rdp-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Install LXDE and XRDP
      run: |
        sudo apt update
        sudo apt install -y lxde-core xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Create a user for RDP
      run: |
        sudo adduser --disabled-password --gecos "" myuser
        echo "myuser:123456" | sudo chpasswd
        sudo usermod -aG sudo myuser

    - name: Download and Run Playit
      run: |
        curl -L https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-amd64 -o playit
        chmod +x playit
        ./playit --secret 7926284faf370476c927d1b4e0a8204e808c4fa9d1088f3d20fc645056b40004
