name: Linux RDP Tunnel with Playit (Binary Method)

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Install XFCE and xrdp
      run: |
        sudo apt update
        sudo apt install -y xrdp xfce4 xfce4-goodies
        echo "xfce4-session" > ~/.xsession
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Set password for default user
      run: |
        echo 'runner:p@ssw0rd!' | sudo chpasswd

    - name: Download Playit Binary
      run: |
        wget https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-amd64 -O playit
        chmod +x playit

    - name: Run Playit with stdin secret
      run: |
        echo "playit-auth:7926284faf370476c927d1b4e0a8204e808c4fa9d1088f3d20fc645056b40004" | ./playit
